#-----------------------------------------------------------------------------------------------------#
# 							GENERAL INFORMATION
#-----------------------------------------------------------------------------------------------------#
# File description:
#	Name
#	Bedmethyl.R
#
#	Purpose 
#		This code was made for preprocessing bedmethyl files generated by the ModKit tool
#
# Author comment:
#	Lisa Koole
#	lisa.koole@maastrichtuniversity.nl
#
#

#-----------------------------------------------------------------------------------------------------#
# 							1. Main settings                                     ----
#-----------------------------------------------------------------------------------------------------#

# Get all general settings 
s_ROOT_dir <<- "add/path/to/root/directory"
source(paste0(s_ROOT_dir,"Scripts/.Main/Settings_v2.R"))


# library(profvis)
# profvis({
#   data(diamonds, package = "ggplot2")
#   
#   plot(price ~ carat, data = diamonds)
#   m <- lm(price ~ carat, data = diamonds)
#   abline(m, col = "red")
# })

#-----------------------------------------------------------------------------------------------------#
# 							2. Load libraries needed                             ----
#-----------------------------------------------------------------------------------------------------#
library(dplyr)
library(data.table)
library(purrr)
library(tidyverse)
library(stringr)
library(readxl)
library(envnames)
library(pbapply)
library(rstatix)

#-----------------------------------------------------------------------------------------------------#
# 							3. Process bedmethyl data                            ----
#-----------------------------------------------------------------------------------------------------#

# Create list of bedmethyl files to import
temp = list.files(s_bedfiles_folder, pattern="\\.bed$", full.names = TRUE)
cat(paste0("number of samples: " , length(temp)))

pblapply(temp, function(x) {
  
  # Load bedmethyl file and select relevant columns
  bedfile <- tryCatch({fread(x, header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="",
                             colClasses =c("character", "integer", "NULL", "character", "numeric",
                                           "NULL", "NULL", "NULL", "NULL", "NULL", "numeric",
                                           "integer", "integer", "NULL", "NULL", "NULL", "NULL", "NULL"))
  }, error = function(e) {
    warning(paste("Error reading file:", x, "-", e$message))
    return(NULL)
  })
  
  if (is.null(bedfile)) return(NULL)

  # Rename columns of interest
  bedfile <- setNames(bedfile, c("chrom", "start_pos0", "mod_base_code","score",
                                 "percent_mod", "N_mod", "N_canon"))
  
  # Extract the base name of the file
  file_base_name <- sub("_filtered_SQK-NBD114-24", "",basename(x))
  
  # Extract postions
  position <- paste0(bedfile$chrom, "_", as.character(bedfile$start_pos0))

  # Extract 5mC values
  rows_with_m <- bedfile$mod_base_code== "m"
  methyl <- data.frame("position" = position[rows_with_m], "percent_mod" = bedfile$percent_mod[rows_with_m])
  methyl_count <- data.frame("position" = position[rows_with_m], "N_mod" = bedfile$N_mod[rows_with_m])
  
  # Extract 5hmC values
  rows_with_h <- bedfile$mod_base_code== "h"
  hydroxymethyl <- data.frame("position" = position[rows_with_h], "percent_mod" = bedfile$percent_mod[rows_with_h])
  hydroxymethyl_count <- data.frame("position" = position[rows_with_h], "N_mod" = bedfile$N_mod[rows_with_h])
  
  # Extract combined 5mC and 5hmC values
  modified_perc <- 100 - (bedfile$N_canon/bedfile$score)*100
  modified_perc <- unique(data.frame(position, modified_perc))
  
  # Extract combined 5mC and 5hmC counts
  modified_count <- bedfile$score - bedfile$N_canon
  modified_count <- unique(data.frame(position, modified_count))
  
  # Extract scores (number of calls)
  scores <- unique(data.frame(position, "scores" = as.numeric(bedfile$score)))
  
  # Save processed data
  bed_out_dir <- file.path(s_project_folder, "Bedmethyl")
  
  tryCatch(saveRDS(bedfile, file = file.path(bed_out_dir, paste0(file_base_name, ".rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(methyl, file = file.path(bed_out_dir, paste0(file_base_name, "_methyl.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(hydroxymethyl, file = file.path(bed_out_dir, paste0(file_base_name, "_hydroxymethyl.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(modified_perc, file = file.path(bed_out_dir, paste0(file_base_name, "_modified.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(scores, file = file.path(bed_out_dir, paste0(file_base_name, "_scores.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(methyl_count, file = file.path(bed_out_dir, paste0(file_base_name, "_methyl_count.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(hydroxymethyl_count, file = file.path(bed_out_dir, paste0(file_base_name, "_hydroxymethyl_count.rds"))), error = function(e) warning(e$message))
  tryCatch(saveRDS(modified_count, file = file.path(bed_out_dir, paste0(file_base_name, "_modified_count.rds"))), error = function(e) warning(e$message))
  
  # Free up memory
  rm(bedfile, methyl, hydroxymethyl, modified_perc, scores, methyl_count, hydroxymethyl_count, modified_count)
  gc()
})


#-----------------------------------------------------------------------------------------------------#
# 				4. Load pheno data and determine CaseIDs                              ----
#-----------------------------------------------------------------------------------------------------#

# Load pheno data
load(paste0(s_ROOT_dir,s_out_folder,"Pheno/Pheno.Rdata")) 

# Create temporary list with saved bedmethyl files
temp = list.files(file.path(s_project_folder, "Bedmethyl/"), pattern=paste0("\\.bam.bed.rds$"), 
                  full.names = TRUE)

# Extract the file basename (Sample Name)
file_base_name <- sub(".bam.bed.*", "", basename(temp))

# Match pheno information to samples included in data set
samples <- data.frame("Barcode" = sub(".*barcode","barcode", file_base_name),
                      "Flowcell" = sub("_barcode.*", "", file_base_name))



# Check for values that do not match 
cat("Values in pheno but not in samples: \n")
print(setdiff(pheno[,c("Barcode", "Flowcell")], samples))  # Values in pheno not in samples

cat("Values in samples but not in pheno: \n")
print(setdiff(samples, pheno[,c("Barcode", "Flowcell")]))  # Values in samples not in pheno



# Set sample names
pheno_subset <- inner_join(samples, pheno, by = c("Flowcell", "Barcode")) 
sample_names <- paste0("sample_", pheno_subset$CaseID)
pheno_subset <- cbind(pheno_subset, sample_names)

# Free up memory
rm(pheno, sample_names)
gc()

#-----------------------------------------------------------------------------------------------------#
#					  5. Create dataframe for 5mC, 5hmC and canonical values       ----
#-----------------------------------------------------------------------------------------------------#

# Function for creating dataframes with CpGs (rows) and samples (columns)
combine_perc <- function(mod_type, chunk_size) {
  
  files = list.files(file.path(s_project_folder, "Bedmethyl/"), 
                    pattern=paste0("\\.bed_", mod_type, ".rds$"), 
                    full.names = TRUE)
  
  # calculate number of chunks
  files = split(files, ceiling(seq_along(files)/chunk_size))
  chunks = 1:length(files)
  
  sample_names = split(pheno_subset$CaseID, ceiling(seq_along(pheno_subset$CaseID)/chunk_size))
  
  cat("Number of samples: ", print(chunk_size*length(files)))
  
  # Merge samples
  pblapply(chunks, function(chunk) {
    
    temp <- files[[chunk]]
    
    bedfiles_chunk <- readRDS(temp[1]) # Start with first sample
    
    progress_bar <- txtProgressBar(min=0, max=length(temp)) # Add progress bar
    
    for (i in 2:length(temp)) {
      # Read BED file
      file <- readRDS(temp[i])
      file_base_name <- sub(".bam.bed.*", "", basename(temp[i]))
      
      # Combine methyl values
      bedfiles_chunk <- full_join(bedfiles_chunk, file, by = "position")
      colnames(bedfiles_chunk)[1] <- c("position")
      colnames(bedfiles_chunk)[i] <- sub(".bam.bed.*", "", basename(temp[i-1])) # existing data frame
      colnames(bedfiles_chunk)[i+1] <- sub(".bam.bed.*", "", basename(temp[i])) # new data frame
      
      rm(file)
      gc()
      
      setTxtProgressBar(progress_bar, value = i)
    }
    
    # Move position values to rownames
    rownames(bedfiles_chunk) <- bedfiles_chunk$position
    bedfiles_chunk <- bedfiles_chunk %>% dplyr::select(!(position))
    
    # Set sample names
    names(bedfiles_chunk) <- paste0("sample_", sample_names[[chunk]])
    
    # save
    saveRDS(bedfiles_chunk, file = file.path(s_OUT_dir, "Bedmethyl_all/", paste0("bedfiles_", mod_type,"_chunk_",chunk,".rds")))
    gc()
    
    
  })
  
  temp = list.files(file.path(s_OUT_dir, "Bedmethyl_all/"), 
                    pattern=paste0("bedfiles_", mod_type, "_chunk_"), 
                    full.names = TRUE)
  
  bedfiles_all <- readRDS(temp[1]) # Start with first chunk
  
  progress_bar <- txtProgressBar(min=0, max=length(temp)) # Add progress bar
  
  for (i in 2:length(temp)) {
    # Read BED file
    file <- readRDS(temp[i])
    
    
    # Combine methyl values
    bedfiles_all <- merge(bedfiles_all, file, by = "row.names", all=TRUE)
    rownames(bedfiles_all) <- c("Row.names")
    bedfiles_all <- bedfiles_all[,-1]
    
    rm(file)
    gc()
    
    setTxtProgressBar(progress_bar, value = i)
  }
  
  saveRDS(bedfiles_all, file = file.path(s_OUT_dir, "Bedmethyl_all/", paste0("bedfiles_", mod_type,"_all",".rds")))
  gc()
}





# Use combine_perc function for all types of modifications
combine_perc("methyl", chunk_size=50)
combine_perc("hydroxymethyl", chunk_size=40)
combine_perc("modified", chunk_size=40)


#-----------------------------------------------------------------------------------------------------#
#					  6. Create dataframe for counts                                      ----
#-----------------------------------------------------------------------------------------------------#

# Function for creating dataframes with CpGs (rows) and samples (columns) counts
combine_counts <- function(mod_type) {
  
  temp = list.files(file.path(s_project_folder, "Bedmethyl/"), 
                    pattern=paste0("\\.bed_", mod_type, ".rds$"), 
                    full.names = TRUE)
  
  print(length(temp))
  
  bedfiles_all <- readRDS(temp[1]) # Start with first sample
  
  progress_bar <- txtProgressBar(min=0, max=length(temp)) # Add progress bar
  
  for (i in 2:length(temp)) {
    # Read BED file
    file <- readRDS(temp[i])
    file_base_name <- sub(".bam.bed.*", "", basename(temp[i]))
    
    # Combine methyl values
    bedfiles_all <- full_join(bedfiles_all, file, by = "position")
    colnames(bedfiles_all)[1] <- c("position")
    colnames(bedfiles_all)[i] <- sub(".bam.bed.*", "", basename(temp[i-1])) # existing data frame
    colnames(bedfiles_all)[i+1] <- sub(".bam.bed.*", "", basename(temp[i])) # new data frame
    
    rm(file)
    gc()
    
    setTxtProgressBar(progress_bar, value = i)
  }
  
  # Move position values to rownames
  rownames(bedfiles_all) <- bedfiles_all$position
  bedfiles_all <- bedfiles_all %>% dplyr::select(!(position))
  
  # Set sample names
  names(bedfiles_all) <- paste0("sample_", pheno_subset$CaseID)
  
  # Impute zeros
  bedfiles_all[is.na(bedfiles_all)] <- 0

  # # Extract the base name of the file
  # file_base_name <- sub("bedfiles_", "", sub("_all.rds*", "", basename(scores_file)))
  
  # save
  saveRDS(bedfiles_all, file = file.path(s_OUT_dir, "Bedmethyl_all/", paste0("bedfiles_", mod_type,"_all.rds")))
  gc()
}

combine_counts("scores")
combine_counts("methyl_count")
combine_counts("hydroxymethyl_count")
combine_counts("modified_count")



# Impute zero in scores file (in case too much for combine_counts function)

# impute_zero <- function(scores_file) {
#   
#   # Extract counts or scores (= total coverage)
#   scores = readRDS(scores_file)
#   scores[is.na(scores)] <- 0
#   
#   # Extract the base name of the file
#   file_base_name <- sub("bedfiles_", "", sub("_all.rds*", "", basename(scores_file)))
#   
#   saveRDS(scores, file = paste0(s_OUT_dir, "Bedmethyl_all/", "bedfiles_", file_base_name, "_all.rds"))
#   gc()
# }
# 
# temp = list.files(file.path(s_OUT_dir, "Bedmethyl/"), pattern="count_all.rds", 
#                   full.names = TRUE)
# 
# pblapply(temp, function(x) impute_zero(x))



